### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by milesgranger**
Adds a first attempt at a logo, probably a placeholder for now.. but more importantly updates that we can install the project via `pip`

### CODE REVIEW

**Comment by epa095** [comment]
Can we actually use the logo? I.e., how was it made? If it is a stitched-together collection of symbols then where did they come from? Thinking about copyright here.

**Comment by milesgranger** [comment]
https://www.freelogodesign.org/

Guess the burden of responsibility is on them.

**Review by flikka — DISMISSED** [review]
I love it! BUT: The logo is too big and centered. Can you make it a bit smaller, and write Gordo on the side?

**Comment by Natalie-Caruana** [comment]
Other than the arrows I like it :) ...how about if we replace the arrows with regular lines and enclose logo in a circle?

**Review by epa095 — COMMENTED** [review]
I propose you remove the logo, and we can bikeshed over that forever, but then we can merge the other stuff

**Review by epa095 — APPROVED** [review]
LGTM. @flikka  remove your objections plz!

**Pull request merged**
