### PR TITLE
Update tmp_dir fixture to yield teardown pattern

### PR DESCRIPTION
**Pull request by ryanjdillon**
# Problem :beer: 
The fixture for creating a temporary directory leaves behind some tmp-crud at times.

# Solution :ireland: 
This uses a context manager with a yield to make sure its cleaned up aftwerwards.

### CODE REVIEW

**Review by milesgranger — COMMENTED** [review]
Looks good, but the commit does more than what it says.

**Comment by flikka** [comment]
> Looks good, but the commit does more than what it says.

But not that much more right? Some reformatting and cleaning? Any reason not to approve @milesgranger?

**Review by milesgranger — APPROVED** [review]

**Comment by milesgranger** [comment]
There you go @flikka

**Comment by epa095** [comment]
After a rebase on master I think the tests should pass again  @ryanjdillon

**Pull request merged**
