### PR TITLE
Add a base_path argument to NCS reader

### PR DESCRIPTION
**Pull request by flikka**
Instead of hard-coding demo assets or other cases where you want to decide the base path (testing, demos) - provide a parameter for it.

### CODE REVIEW

**Review by epa095 — CHANGES_REQUESTED** [review]
I propose we rather add an optional parameter to the data lake data reader `base_path` which, if provided, is used as the base-path, ignoring assets completly

**Comment by flikka** [comment]
> I propose we rather add an optional parameter to the data lake data reader `base_path` which, if provided, is used as the base-path, ignoring assets completly

Yepp.

**Review by epa095 — APPROVED** [review]
You tested it? It looks pretty good to me.

Edit: except the way-to-long commit message of course!!!

**Comment by epa095** [comment]
Should we merge this in before a release @flikka  ?

**Pull request merged**
